@startmindmap
<style>
mindmapDiagram 
{
  .center {
    HyperlinkColor Black
    BackgroundColor lightblue
    HyperlinkUnderlineThickness 0
    HyperlinkUnderline false
  }
  .link {
    HyperlinkColor LightSeaGreen
    HyperlinkUnderlineThickness 0
    HyperlinkUnderline false
  }
  .blue {
    LineColor lightblue
  }
}
</style>

* [[https://github.com/terkelg/awesome-creative-coding Creative coding]] <<center>>

**_ Audio
***_ [[https://sonification.design/ Sonification]] <<link>>
***_ Noise
***_ Music
****_ Live coding
*****_ [[https://tidalcycles.org/ Tidal cycles]] <<link>>
*****_ [[https://strudel.tidalcycles.org/ Strudel]] <<link>>
*****_ [[https://sonic-pi.net/ Sonic Pi]] <<link>>
*****_ [[https://sardine.raphaelforment.fr/ Sardine]] <<link>>
*****_ [[https://supercollider.github.io/ SuperCollider]] <<link>>
****_ Visual programming
*****_ [[https://puredata.info/ Pure Data]] <<link>>
*****_ [[https://cycling74.com/products/max Max]] <<link>>
*****_ [[https://www.bespokesynth.com/ Bespoke]] <<link>>
*****_ [[https://www.iannix.org/en/whatisiannix/ Iannix]] <<link>>
****_ Generative music
*****_ [[https://opusmodus.com/ OpusModus]] <<link>>
*****_ MIDI generators
****_ Esoteric
*****_ [[https://dollchan.net/bytebeat/ Bytebeat]] <<link>>
*****_ [[https://hundredrabbits.itch.io/orca Orca]] <<link>>

***_ Sound synthesis
****_ [[https://csound.com/ Csound]] <<link>>
****_ [[https://faust.grame.fr/ Faust]] <<link>>
****_ [[https://supercollider.github.io/ SuperCollider]] <<link>>

**_ Graphics
***_ Sketching
****_ [[https://processing.org/ Processing]] <<link>>
****_ [[https://p5js.org/ P5js]] <<link>>
***_ Live coding
****_ [[https://teddavis.org/p5live P5Live]] <<link>>
****_ [[https://hydra.ojack.xyz/ Hydra]] <<link>>
***_ [[https://thebookofshaders.com/{What are shaders?} Shaders]] <<link>>
****_ [[https://www.shadertoy.com/ Shadertoy]] <<link>>
****_ [[https://shadered.org/ Shadered]] <<link>>
****_ [[https://thecodetherapy.com/ Code Therapy]] <<link>>
****_ [[https://hexler.net/kodelife Kodelife]] <<link>>
****_ [[https://www.visor.live/ Visor]] <<link>>
***_ 3D / VR / AR
****_ [[https://threejs.org/ Threejs]] <<link>>
****_ [[https://aframe.io/ A-Frame]] <<link>>
****_ [[https://playground.babylonjs.com/ Babylonjs]] <<link>>
***_ AI
****_ [[https://magenta.tensorflow.org/demos Magneta]] <<link>>
****_ [[https://huggingface.co/spaces/ Huggingface spaces]] <<link>>
****_ [[https://github.com/amrzv/awesome-colab-notebooks Colab notebooks]] <<link>>

***_  Data visualization
****_ Infographics
*****_ [[https://d3js.org/ D3js]] <<link>>
*****_ [[https://vis.gl/frameworks Vis.gl]] <<link>>
****_ [[https://www.ted.com/playlists/201/art_from_data Data art]] <<link>>
***_ Unconventional
****_ [[https://asciicker.com/ Asciiker]] <<link>>
****_ [[https://github.com/harry7557558/spirula Function graphing]] <<link>>
****_ [[https://excelunusual.com/ Excel unusual]] <<link>>

**_ Text
***_ [[https://timrodenbroeker.de/processing-tutorial-kinetic-typography-1 Kinetic typography]] <<link>>
***_ [[https://play.ertdfgcvb.xyz/ ASCII art]] <<link>>
***_ [[https://github.com/coreybobco/generativepoetry-py Poetry]] <<link>>
***_ [[https://nanogenmo.github.io/ Stories]] <<link>>

**_ Games
***_ Text adventures
****_ Interactive fiction
****_ Visual novels
***_ Rhythm games
***_ Generative content
****_ Landscape
****_ Monsters
****_ Quests
***_ Graphic adventures
****_ 2D
****_ 3D

**_ Programming programming
***_ [[https://eloquentjavascript.net/12_language.html New languages]] <<link>>
***_ [[http://craftinginterpreters.com/ Crafting interpreters (BOOK)]] <<link>>
***_ Metaprogramming
***_ Monkeypatching
***_ [[https://esolangs.org/wiki/Main_Page Esolangs]] <<link>>

**_ Physical
***_ [[https://xyzdims.com/2023/02/09/3d-printing-parametric-generative-3d-infill-geometries/ 3D printing]] <<link>>
***_ Architecture
***_ Electronics
****_ Kits
*****_ Arduino
*****_ Teensy
*****_ Raspberry Pi Zero
****_ Modular synths
****_ Robotics
****_ Wearables
*****_ Sewable electronics
*****_ Electronic jewelry
*****_ Cosplay

--_ Scenes

---_ Performative
----_ Digital arts
-----_ Installation artworks
-----_ Interactive art
-----_ Dance choreography
----_ [[https://github.com/toplap/awesome-livecoding Live coding]] <<link>>
-----_ Human interaction
-----_ Music
-----_ Visualization

---_ Competitive
----_ [[https://github.com/psykon/awesome-demoscene Demoscene]] <<link>>
-----_ Demoparties
-----_ Shader showdowns
-----_ [[https://assembly.org/en Assembly]] <<link>>
----_ [[https://github.com/lnishan/awesome-competitive-programming Sports]] <<link>>
-----_ [[https://robocode.sourceforge.io/ Robocode]] <<link>>
-----_ [[https://codeforces.com/ Codeforces]] <<link>>
-----_ [[https://codegolf.stackexchange.com/ Code golfing]] <<link>>
-----_ [[https://www.fmworldcup.com/ Excel championship]] <<link>>
----_ [[https://hackathon.guide/ Hackathons]] <<link>>
-----_ Datathons
-----_ [[https://www.finnishgamejam.com/ Game jams]] <<link>>
-----_ [[https://ultrahack.org/ Ultrahack]] <<link>>
-----_ [[https://www.hackjunction.com/ Junction]] <<link>>

---_ Educative
----_ [[https://scratch.mit.edu/ Scratch]] <<link>>
----_ [[https://code.org/ Code.org]] <<link>>

--_ Hardware
---_ Computer
----_ Keyboard
----_ Mouse
----_ USB
---_ Mobile
----_ Touch
---_ Console
----_ Wiimote
----_ Kinect
----_ PS Eye
---_ Goggles
----_ VR
----_ AR
----_ Smart
---_ AV controllers
----_ MIDI
----_ OSC
----_ DMX
---_ Output
----_ Screens
----_ Oscilloscope
----_ Projectors
----_ Lightshow
----_ Drone fireworks
---_ DIY

--_ Algorithms
---_ Random
---_ Noise
---_ Algorithmic patterns
----_ Mathematical models
----_ Grammars
----_ Raymarching
----_ Rewriting systems
-----_ Fractal algorithms
-----_ Cellular automata
-----_ L-system
----_ [[https://theresanaiforthat.com/ AI patterns]] <<link>>
-----_ Markov chains
-----_ NLP
-----_ Statistical

--_ Data
---_ Structured
----_ Nature
-----_ [[https://www.ableton.com/en/blog/sound-the-alarm-data-sonification-as-a-tool-for-climate-action/ Weather]] <<link>>
-----_ [[https://www.system-sounds.com/ Space]] <<link>>
-----_ [[https://en.wikipedia.org/wiki/Protein_music DNA]] <<link>>
----_ Economy
-----_ Statistics
-----_ Expences
-----_ Currency
-----_ [[https://www.bitlisten.com/ Bitcoin]] <<link>>
----_ Temporal
-----_ Chess
-----_ Covid
-----_ Github
----_ Spatial
-----_ Animal migration
-----_ GIS
---_ Unstructured
----_ Books
----_ Images
----_ Audio
----_ Video
@endmindmap