@startmindmap
<style>
mindmapDiagram 
{
  node {
    Margin 25
    Padding 15
    LineThickness 0.5
    FontName Consolas
  }
  node {
    :depth(0) {
      FontSize 20
    }
    :depth(1) {
      FontSize 18
    }
  }
  boxless {
    Margin 15
    FontColor Black
  }
  arrow {
    Maring 100
    LineStyle 0
    LineThickness 1.0
    LineColor Black
  }
  .center {
    HyperlinkColor RoyalBlue
    BackgroundColor lightblue
    HyperlinkUnderlineThickness 0
    HyperlinkUnderline false
  }
  .link {
    Padding 15
    HyperlinkColor RoyalBlue
    HyperlinkUnderlineThickness 0
    HyperlinkUnderline false
  }
}
</style>

skinparam svgLinkTarget _blank

* [[https://github.com/terkelg/awesome-creative-coding #creativecoding]] <<center>>

**_ Audio
***_ [[https://sonification.design/ Sonification]] <<link>>
***_ Noise
***_ Music
****_ [[https://livecodingbook.toplap.org Live coding]] <<link>>
*****_ [[https://topos.live Topos]] <<link>>
*****_ [[https://tidalcycles.org/ Tidal cycles]] <<link>>
*****_ [[https://strudel.tidalcycles.org/ Strudel]] <<link>>
*****_ [[https://sonic-pi.net/ Sonic Pi]] <<link>>
*****_ [[https://sardine.raphaelforment.fr/ Sardine]] <<link>>
*****_ [[https://supercollider.github.io/ SuperCollider]] <<link>>
*****_ Scales
******_ [[https://www.huygens-fokker.org/scala/ Scala]] <<link>>
******_ [[https://en.xen.wiki/w/Main_Page Xenharmonics]] <<link>>
******_ [[https://scaleworkshop.plainsound.org Scale workshop]] <<link>>
****_ Visual programming
*****_ [[https://puredata.info/ Pure Data]] <<link>>
*****_ [[https://cycling74.com/products/max Max]] <<link>>
*****_ [[https://www.bespokesynth.com/ Bespoke]] <<link>>
*****_ [[https://www.iannix.org/en/whatisiannix/ Iannix]] <<link>>
****_ Generative music
*****_ [[https://opusmodus.com/ OpusModus]] <<link>>
*****_ MIDI generators
****_ Esoteric
*****_ [[https://dollchan.net/bytebeat/ Bytebeat]] <<link>>
*****_ [[https://hundredrabbits.itch.io/orca Orca]] <<link>>

***_ Sound synthesis
****_ [[https://csound.com/ Csound]] <<link>>
****_ [[https://faust.grame.fr/ Faust]] <<link>>
****_ [[https://supercollider.github.io/ SuperCollider]] <<link>>

**_ Graphics
***_ Sketching
****_ [[https://processing.org/ Processing]] <<link>>
****_ [[https://p5js.org/ P5js]] <<link>>
***_ Live coding
****_ [[https://teddavis.org/p5live P5Live]] <<link>>
****_ [[https://hydra.ojack.xyz/ Hydra]] <<link>>
****_ [[https://livecodingyoutube.github.io Livecodingyoutube]] <<link>>
***_ [[https://thebookofshaders.com/{What are shaders?} Shaders]] <<link>>
****_ [[https://www.shadertoy.com/ Shadertoy]] <<link>>
****_ [[https://shadered.org/ Shadered]] <<link>>
****_ [[https://thecodetherapy.com/ Code Therapy]] <<link>>
****_ [[https://hexler.net/kodelife Kodelife]] <<link>>
****_ [[https://www.visor.live/ Visor]] <<link>>
***_ 3D / VR / AR
****_ [[https://threejs.org/ Threejs]] <<link>>
****_ [[https://aframe.io/ A-Frame]] <<link>>
****_ [[https://playground.babylonjs.com/ Babylonjs]] <<link>>
***_ AI
****_ [[https://magenta.tensorflow.org/demos Magneta]] <<link>>
****_ [[https://huggingface.co/spaces/ Huggingface spaces]] <<link>>
****_ [[https://github.com/amrzv/awesome-colab-notebooks Colab notebooks]] <<link>>
****_ [[https://github.com/comfyanonymous/ComfyUI Comfy UI]] <<link>>

***_  Data visualization
****_ Infographics
*****_ [[https://d3js.org/ D3js]] <<link>>
*****_ [[https://vis.gl/frameworks Vis.gl]] <<link>>
****_ [[https://www.ted.com/playlists/201/art_from_data Data art]] <<link>>
***_ Unconventional
****_ [[https://asciicker.com/ Asciiker]] <<link>>
****_ [[https://github.com/harry7557558/spirula Function graphing]] <<link>>
****_ [[https://excelunusual.com/ Excel unusual]] <<link>>

**_ Text
***_ [[https://timrodenbroeker.de/processing-tutorial-kinetic-typography-1 Kinetic typography]] <<link>>
***_ [[https://github.com/khrome/ascii-art-docs/blob/master/History.md ASCII art]] <<link>>
****_ [[https://gitlab.com/adelfaure/oscii OSCII editor]] <<link>>
****_ [[https://play.ertdfgcvb.xyz/ ASCII play]] <<link>>
****_ [[https://github.com/JuliaPoo/AsciiArtist Ascii generator]] <<link>>
****_ [[https://github.com/nurpax/petmate PETSCII]] <<link>>
***_ [[https://github.com/coreybobco/generativepoetry-py Poetry]] <<link>>
***_ [[https://nanogenmo.github.io/ Stories]] <<link>>

**_ Games
***_ Text adventures
****_ [[https://github.com/tajmone/awesome-interactive-fiction Interactive fiction]] <<link>>
****_ [[https://www.renpy.org/ Visual novels]] <<link>>
****_ [[https://adelfaure.net/games/ ASCII games]] <<link>>

***_ Generative content
****_ [[https://urn.fi/URN:NBN:fi:tuni-202304234159 Terrain]] <<link>>
****_ [[https://www.kylehuang.design/monstergan Monsters]] <<link>>
****_ [[https://github.com/gknappattack/DRAGN-Town-Quests Quests]] <<link>>
***_ Graphic adventures
****_ 2D graphics
*****_ [[https://gamemaker.io/en GameMaker]] <<link>>
*****_ [[https://github.com/topics/point-and-click Point and Click]] <<link>>
****_ 3D graphics
*****_ [[https://unity.com/ Unity]] <<link>>
*****_ [[https://www.unrealengine.com/en-US Unreal]] <<link>>
***_ [[https://github.com/topics/rhythm-game Rhythm games]] <<link>>

**_ Programming
***_ [[https://esolangs.org/wiki/Main_Page Esolangs]] <<link>>
****_ [[https://esolangs.org/wiki/MUSYS Musys]] <<link>>
****_ [[https://www.uiua.org Uiua]] <<link>>
***_ Parsing
****_ Parser grammars (PEGs)
****_ Recursive descent parsing
***_ [[https://eloquentjavascript.net/12_language.html New languages]] <<link>>
****_ Generic
****_ Time critical
*****_ Ziffers
*****_ TidalCycles
***_ Monkeypatching

**_ Physical
***_ [[https://github.com/topics/generative-design Generative design]] <<link>>
****_ [[https://xyzdims.com/2023/02/09/3d-printing-parametric-generative-3d-infill-geometries/ 3D printing]] <<link>>
****_ [[https://dynamobim.org/ Architecture]] <<link>>
***_ Electronics
****_ Kits
*****_ Arduino
*****_ Teensy
*****_ Raspberry Pi Zero
****_ [[https://github.com/topics/modular-synthesizers Modular synths]] <<link>>
****_ [[https://github.com/topics/robotics Robotics]] <<link>>
****_ [[https://github.com/topics/wearables Wearables]] <<link>>
*****_ [[https://learn.adafruit.com/lets-put-leds-in-things/sewable-circuits Sewable electronics]] <<link>>
*****_ Electronic jewelry
*****_ Cosplay
****_ Musical instruments
*****_ [[https://www.makermusicfestival.com/ Maker music festival]] <<link>>
*****_ [[https://instrumentinventors.org/ Instrument inventors]] <<link>>
****_ [[https://en.wikipedia.org/wiki/Drone_art Drone art]] <<link>>
*****_ [[https://crazyswarm.readthedocs.io/en/latest/ Crazyswarm]] <<link>>
*****_ [[https://skybrush.io/ Skybrush]] <<link>>

--_ Scenes

---_ Performative
----_ Digital arts
-----_ [[https://www.trendhunter.com/slideshow/interactive-art-installations Interactive]] <<link>>
------_ Digital Art Museums
------_ Spaces
------_ Installations
-----_ Augmented
------_ Graffiti
------_ Paintings
-----_ Entangled
------_ Choreography
------_ Holograms
------_ Telematic

----_ VJ culture
-----_ Music videos
-----_ Gigs


----_ [[https://github.com/toplap/awesome-livecoding Live coding]] <<link>>
-----_ Human interaction
-----_ Music
-----_ Visualization


---_ Competitive
----_ [[https://github.com/psykon/awesome-demoscene Demoscene]] <<link>>
-----_ Demoparties
-----_ Shader showdowns
-----_ [[https://assembly.org/en Assembly]] <<link>>
----_ [[https://github.com/lnishan/awesome-competitive-programming Sports]] <<link>>
-----_ [[https://robocode.sourceforge.io/ Robocode]] <<link>>
-----_ [[https://codegolf.stackexchange.com/ Code golfing]] <<link>>
-----_ [[https://www.fmworldcup.com/ Excel championship]] <<link>>
----_ [[https://hackathon.guide/ Hackathons]] <<link>>
-----_ Datathons
-----_ [[https://www.finnishgamejam.com/ Game jams]] <<link>>
-----_ [[https://ultrahack.org/ Ultrahack]] <<link>>
-----_ [[https://www.hackjunction.com/ Junction]] <<link>>

---_ Crafting
----_ Community workspaces
-----_ [[https://hacklab.fi/index_en.html Hacklabs]] <<link>>
-----_ [[https://directory.libraries.fi/services/room/pajamakerspace Makerspaces]] <<link>>
----_ Online learning communities
-----_ [[https://forums.adafruit.com/ Adafruit]] <<link>>
-----_ [[https://forum.arduino.cc/ Arduino]] <<link>>


---_ Hacking
----_ [[https://monoskop.org/Hacker_culture Hacker Culture]] <<link>>
----_ Hacktivism
----_ Digital sovereignty
-----_ Open source
-----_ Local-first
-----_ Anti-Cencorship
-----_ Cracking
-----_ Reverse engineering
-----_ Hardware hacking
----_ Fun geeky stuff
----_ Neckbeard stuff
----_ Hacking Arts




--_ Theory
---_ Music theory
----_ [[https://viva.pressbooks.pub/openmusictheory/part/20th-and-21st-century-techniques/ Post-tonal techniques]] <<link>>
----_ [[https://viva.pressbooks.pub/openmusictheory/chapter/intervals-in-integer-notation/ Integer notation]] <<link>>
----_ [[https://musictheory.pugetsound.edu/mt21c/Serialism.html Serialism]] <<link>>
----_ [[https://musictheory.pugetsound.edu/mt21c/Minimalism.html Minimalism]] <<link>>
----_ [[https://en.wikipedia.org/wiki/Generative_music Generative music]] <<link>>
----_ [[https://atchai.com/blog/2016-02-09-john-coltrane-nicolas-slonimsky-and-the-arduino-part-1/ Slonimsky patterns]] <<link>>
----_ [[https://en.wikipedia.org/wiki/Schillinger_system Schillinger system]] <<link>>
----_ [[https://en.wikipedia.org/wiki/Tintinnabuli Tintinnabuli]] <<link>>
----_ [[http://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf Euclidean rhythm]] <<link>>


---_ Physics
---_ Electronics
---_ Aesthetics
---_ Cognitive
---_ Pedagogy


---_ Algorithmic
----_ Chaos theory
-----_ Fractals
-----_ Feedback loops
-----_ Pendulums
-----_ Self-similarity
----_ Randomness
----_ Noise
----_ [[https://en.m.wikipedia.org/wiki/A*_search_algorithm Pathfinding]] <<link>>
----_ Raymarching
----_ Grammars
----_ Rewriting systems
-----_ Cellular automata
-----_ L-system
----_ [[https://theresanaiforthat.com/ AI]] <<link>>
-----_ Classic
------_ Markov chains
------_ Monte-Carlo methods
-----_ Modern
------_ Machine learning
------_ Multimodal LLMs
-----_ Issues
------_ Originality
------_ Emotions
------_ Dehumanization
------_ Ethics


---_ Math
----_ Trigonometry
----_ Linear algebra
----_ [[https://oeis.org Integer sequences]] <<link>>
----_ Set theory
----_ Graph theory
----_ Game theory
----_ Propability


--_ Hardware
---_ Keyboard
---_ Mouse
---_ Touch
---_ Console
----_ Wiimote
----_ Kinect
----_ PS Eye
---_ VR / AR glasses
---_ AV controllers
----_ MIDI
----_ OSC
----_ DMX
---_ Microcontrollers
----_ Single-board computers
-----_ Raspberry Pi
----_ Development boards
-----_ Cardputer (M5Stack)
----_ IoT kits
---_ Output
----_ Screens
----_ Oscilloscope
----_ [[https://github.com/codingjoe/MusicBeam Projectors]] <<link>>
----_ [[https://github.com/topics/lightshow Lightshow]] <<link>>
----_ [[https://github.com/topics/drone Drones]] <<link>>

--_ Data
---_ Structured
----_ Nature
-----_ [[https://www.ableton.com/en/blog/sound-the-alarm-data-sonification-as-a-tool-for-climate-action/ Weather]] <<link>>
-----_ [[https://www.system-sounds.com/ Space]] <<link>>
-----_ [[https://en.wikipedia.org/wiki/Protein_music DNA]] <<link>>
----_ Economy
-----_ Statistics
-----_ [[https://www.bitlisten.com/ Bitcoin]] <<link>>
----_ Temporal
-----_ Chess
-----_ Covid
-----_ Github
----_ Spatial
-----_ Animal migration
---_ Unstructured
----_ Books
----_ Images
----_ Audio
----_ Video
@endmindmap